services:
  app-dev:
    container_name: settle-app-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: settle-dev
    volumes:
      - ./:/app
    environment:
      - HOST_URL=localhost:5003
    ports:
      - 5003:5002
    profiles:
      - dev
    depends_on:
      - db-connection
    tty: true
    stdin_open: true

  app-prod:
    container_name: settle-app-prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    image: settle-prod
    ports:
      - 5002:5002
    profiles:
      - prod
    depends_on:
      - db-connection
    restart: on-failure

  db-connection:
    container_name: settle-db-connection
    image: mysql
    volumes:
      - ./docker:/app
    command: mysql -hdb-server -uroot -ppassword -e "SET autocommit=0 ; source /app/db.sql ; COMMIT ;"
    depends_on:
      - db-server
    restart: on-failure
    profiles:
      - dev
      - prod

  db-server:
    container_name: settle-db-server
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    volumes:
      - settle:/var/lib/mysql
    profiles:
      - dev
      - prod
  
networks:
  default:
    name: settle

volumes:
  settle:
    name: settle