FROM python:3.9.6

WORKDIR /app
COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . .
RUN python3 -m unittest discover -s test/unit/ -p "*Test.py"

EXPOSE 5002
CMD ["gunicorn", "--bind", "0.0.0.0:5002", "app:app", "--timeout", "300"]
